{% set name = "msgraph-core" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/msgraph_core-{{ version }}.tar.gz
  sha256: a4e42f692e664c60d63359e610bbf990f57b42d8080417261ff7042bbd59c98b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=65.5.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - microsoft-kiota-abstractions >=1.0.0,<2.0.0
    - microsoft-kiota-authentication-azure >=1.0.0,<2.0.0
    - microsoft-kiota-http >=1.0.0,<2.0.0
    - httpx >=0.23.0

test:
  imports:
    - msgraph_core
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/microsoftgraph/msgraph-sdk-python-core
  summary: Core abstractions for kiota generated libraries in Python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/microsoftgraph/msgraph-sdk-python-core
  doc_url: https://github.com/microsoftgraph/msgraph-sdk-python-core/blob/main/README.md

extra:
  recipe-maintainers:
    - xylar
