schema_version: 1

context:
  name: msgraph-core
  version: 1.5.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/msgraph_core-${{ version }}.tar.gz
  sha256: 8ce6a4ffa76d0b4801c2b20df872dd85d4d925b8eceb9809e08d21daba3762cf

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=65.5.0
    - wheel
  run:
    - python >=${{ python_min }}
    - microsoft-kiota-abstractions >=1.13.0,<2.0.0
    - microsoft-kiota-authentication-azure >=1.13.0,<2.0.0
    - microsoft-kiota-http >=1.13.0,<2.0.0
    - httpx >=0.23.0
    # start httpx[http2]
    - h2 >=3,<5
    # end httpx[http2]
tests:
  - python:
      imports:
        - msgraph_core
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  summary: Core abstractions for kiota generated libraries in Python
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/microsoftgraph/msgraph-sdk-python-core
  repository: https://github.com/microsoftgraph/msgraph-sdk-python-core
  documentation: https://github.com/microsoftgraph/msgraph-sdk-python-core/blob/main/README.md

extra:
  recipe-maintainers:
    - xylar
